// styles.js

const ChatbotStyles = {
    container: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      color: 'black',
      justifyContent: 'center',
      height: '100vh',
      width: '100vw',
      backgroundImage: 'url("/wedbackgrounf.png")',
      backgroundSize: 'cover', 
      backgroundPosition: 'center', 
      backgroundRepeat: 'no-repeat', 
    },
      chatWrapper: {
        width: '600px',
        height: '900px',
        backgroundColor: '#fff',
        borderRadius: '16px',
        display: 'flex',
        flexDirection: 'column',
        boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.5)',
        overflow: 'hidden',
      },
      puppyGif: {
        position: 'absolute', 
        top: '10px', 
        left: '50%',
        transform: 'translateX(-50%)', 
        height: '185px',
        width: 'auto',
        zIndex: 10,
      },
      header: {
        height: '80px', 
        backgroundColor: '#ffffff',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 0,
        overflow: 'hidden',
      },
      username: {
        fontSize: '16px',
        marginLeft: '10px',
        fontWeight: 'bold',
      },
      chatWindow: {
          flex: 1,
          padding: '10px',
          overflowY: 'scroll', 
          display: 'flex',
          flexDirection: 'column',
          backgroundColor: '#f5eee6',
          scrollbarWidth: 'none',
          msOverflowStyle: 'none', 
        },
      userMessage: {
        alignSelf: 'flex-end',
        backgroundColor: '#f7bb77',
        font: 'white',
        padding: '8px',
        borderRadius: '16px 0px 16px 16px',
        boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.3)',
        margin: '5px',
        maxWidth: '70%',
      },
      botMessage: {
        alignSelf: 'flex-start',
        backgroundColor: '#f1f0f0',
        padding: '8px',
        borderRadius: '0px 16px 16px 16px',
        boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.3)',
        margin: '5px',
        maxWidth: '70%',
      },
      inputContainer: {
        display: 'flex',
        alignItems: 'center',
        padding: '10px',
        borderTop: '1px solid #ddd',
      },
      input: {
        flex: 1,
        padding: '10px',
        borderRadius: '24px',
        border: '0.1px solid #ddd',
        marginRight: '10px',
      },
      button: {
        backgroundColor: '#fc8a08',
        color: 'white',
        padding: '10px',
        marginLeft: '10px', 
        borderRadius: '20px',
        border: 'none',
        cursor: 'pointer',
      },
      closeButton: {
        backgroundColor: '#7e5bef',
        borderRadius: '50%',
        padding: '10px',
        color: 'white',
        cursor: 'pointer',
      },
    };
    
    export default ChatbotStyles;
    